"""empty message

Revision ID: 17af96d89ebd
Revises: 5cab3ec84331
Create Date: 2017-10-24 21:04:51.011416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17af96d89ebd'
down_revision = '5cab3ec84331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=False)
    op.create_table('profile_blacklist',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'profile_id')
    )
    op.create_table('profile_whitelist',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_whitelist')
    op.drop_table('profile_blacklist')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
