"""empty message

Revision ID: 30121b1c7720
Revises: 
Create Date: 2017-11-02 21:37:52.728595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30121b1c7720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=False)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=True)
    op.create_index(op.f('ix_movie_rating'), 'movie', ['rating'], unique=False)
    op.create_table('profile_blacklist',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'profile_id')
    )
    op.create_table('profile_whitelist',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_whitelist')
    op.drop_table('profile_blacklist')
    op.drop_index(op.f('ix_movie_rating'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
