"""Initial

Revision ID: 5cab3ec84331
Revises: 
Create Date: 2017-10-24 14:16:12.335843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cab3ec84331'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=False)
    op.create_index(op.f('ix_movie_rating'), 'movie', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_rating'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
