"""empty message

Revision ID: ffffb2db6fca
Revises: 17af96d89ebd
Create Date: 2017-10-27 14:26:54.287102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffffb2db6fca'
down_revision = '17af96d89ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movie_name', table_name='movie')
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.create_index('ix_movie_name', 'movie', ['name'], unique=False)
    # ### end Alembic commands ###
